# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  # LEFT normal (split + oled)
  - board: nice_nano_v2
    shield: lily58_left nice_oled
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DCONFIG_ZMK_STUDIO=y
      -DCONFIG_BT_DEVICE_NAME=\"L58-L\"
      -DDTC_OVERLAY_FILE=encoder_right_p029_p031.overlay
    artifact-name: lily58_left_oled_studio

  # RIGHT normal (split + oled)
  - board: nice_nano_v2
    shield: lily58_right nice_oled
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DCONFIG_ZMK_STUDIO=y
      -DCONFIG_BT_DEVICE_NAME=\"L58-R-NEW\"
      -DDTC_OVERLAY_FILE=encoder_right_p029_p031.overlay
    artifact-name: lily58_right_oled_studio

  # settings reset (flashear en LEFT y RIGHT cuando ocupes limpiar bonds)
  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: settings_reset

  # RIGHT: USB test (SIN OLED, BLE apagado)
  - board: nice_nano_v2
    shield: lily58_right
    cmake-args: >
      -DCONFIG_ZMK_STUDIO=y
      -DCONFIG_BT_DEVICE_NAME=\"L58-R-USBTEST\"
      -DCONFIG_ZMK_BLE=n
      -DCONFIG_ZMK_USB=y
      -DCONFIG_ZMK_DISPLAY=n
      -DDTC_OVERLAY_FILE=encoder_right_p029_p031.overlay
    artifact-name: lily58_right_usb_test
