# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  - board: nice_nano_v2
    shield: lily58_left nice_oled
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_BT_DEVICE_NAME=\"L58-L\"
    artifact-name: lily58_left_oled_studio

  - board: nice_nano_v2
    shield: lily58_right nice_oled
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_BT_DEVICE_NAME=\"L58-R-NEW\"
    artifact-name: lily58_right_oled_studio
  # RIGHT solo por USB (para pruebas, NO split)
  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: reset_right_before_usb_test

  - board: nice_nano_v2
    shield: lily58_right nice_oled
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DCONFIG_ZMK_STUDIO=y
      -DCONFIG_BT_DEVICE_NAME=\"L58-R-USBTEST\"
      -DCONFIG_ZMK_BLE=n
      -DCONFIG_ZMK_USB=y
    artifact-name: lily58_right_usb_test
    


